from django.conf import settings
from django.db import models

# Create your models here.
class FoodSearch(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='food_searches')
    query = models.CharField(max_length=200) # The search query entered by the user
    user_lat = models.FloatField() # Latitude of the user's location
    user_lng = models.FloatField() # Longitude of the user's location

    provider = models.CharField(max_length=20)  # The food delivery provider (e.g., Uber Eats, DoorDash)
    expanded_terms = models.JSONField(default=list)  # Expanded search terms generated by the provider's API
    filters = models.JSONField(default=dict)  # Any filters applied to the search (e.g., cuisine type, price range)

    created_at = models.DateTimeField(auto_now_add=True) # Timestamp of when the search was created
    def __str__(self):
        return f"{self.user_id}:{self.query}" # String representation of the FoodSearch model, showing the user ID and search query
    
    class RestaurantResult(models.Model):
        search = models.ForeignKey(FoodSearch, on_delete=models.CASCADE, related_name='results', on_delete=models.CASCADE) # Foreign key linking to the FoodSearch model
        name = models.CharField(max_length=255) # Name of the restaurant
        address = models.CharField(max_length=500, blank=True) # Address of the restaurant

        lat = models.FloatField(null=True, blank=True) # Latitude of the restaurant
        lng = models.FloatField(null=True, blank=True) # Longitude of the restaurant

        distance_m = models.IntegerField(null=True, blank=True) # Distance from the user's location to the restaurant in meters
        rating = models.FloatField(null=True, blank=True) # Rating of the restaurant 
        price_level = models.IntegerField(null=True, blank=True) # Price level of the restaurant
        is_open_now = models.BooleanField(null=True, blank=True) # Whether the restaurant is currently open
        provider_places_id = models.CharField(max_length=200, blank=True) # The unique identifier for the restaurant from the food delivery provider's API
        provider = models.CharField(max_length=20, default="unknown")   # The food delivery provider (e.g., Uber Eats, DoorDash)

    def __str__(self):
        return self.name # String representation of the RestaurantResult model, showing the name of the restaurant
    
    

